### ISSUE TITLE
Update routes proactively when draining node...

### ISSUE THREAD

**Issue by chrismarino** [romana/vpc-router#26]
Nodes are frequently drained of pods for autoscaling, etc. If a routing node is being drained in advance of being taken out of service, reassign the routing node to another instance.

**Comment by chrismarino** [comment]
That is, reassign the routing node to another instance *before* it has been drained and taken out of service. Don't wait for healthcheck to fail to trigger route update.

**Comment by jbrendel** [comment]
This should probably be implemented as an additional health monitoring plugin, which can then be used in conjunction with other health checks via the multi plugin.

It's best to do this in an external health monitoring plugin (its own project), since otherwise we add too many prerequisites and environment specific knowledge into vpc-router itself.

**Comment by jbrendel** [comment]
This will be addressed with issue 11 of the vpcrouter-romana-plugin: https://github.com/romana/vpcrouter-romana-plugin/issues/11
